// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc620.Warbot2017.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import edu.wpi.first.wpilibj.command.WaitCommand;

/**
 *
 */
public class AutoRightStart extends CommandGroup {
    public AutoRightStart() {
    	addSequential(new DriveTime(106));
    	addSequential(new Turn(-60));
//    	addSequential(new AlignForGearPeg(0, .3));
    	addSequential(new DriveUntilDist(11, .5));
    	addSequential(new DriveTime(7));
    	addSequential(new LowerGearArm());
		addParallel(new DriveTime(.5, -.5));
		addSequential(new RaiseGearArm());
    } 
}