package org.usfirst.frc620.Warbot2017.commands;
// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

import org.usfirst.frc620.Warbot2017.Robot;
import org.usfirst.frc620.Warbot2017.subsystems.Climber;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj.command.Command;

/**
*
*/
public class Climb extends Command
{
	private XboxController xbox;
	private long buttonTimer = 0;
	boolean madeContact = false;
	boolean exit = false;
	private int moveTime = 0;
	Climber climber = Robot.climber;
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public Climb(XboxController xboxin)
	{
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		xbox = xboxin;
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		requires(Robot.driveTrain);
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
		setInterruptible(false);
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		Robot.switchToCamera(2);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		if(climber.isDown())
		{
			//TODO: add drive controls
			
			climber.climb(0.3);
			if(xbox.getRawButton(2))
				exit = true;
		}
		else if(!climber.isUp())
		{
			climber.climb(0.5);
			//TODO: fix this
//			if(++moveTime < 3)
//				Robot.driveTrain.mecanumDrive(0, 0, .4, 0);
//			else
//				Robot.driveTrain.mecanumDrive(0, 0, 0.2, 0);
		}
		else if(!climber.isInContact())
			climber.climb(0.8);
		else
		{
			if(!madeContact)
			{
				buttonTimer = System.currentTimeMillis();
				madeContact = true;
			}
			climber.climb(0.3);
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished()
	{
		return exit || (madeContact && System.currentTimeMillis() - buttonTimer >= 250);
	}

	// Called once after isFinished returns true
	protected void end()
	{
		climber.kill();
		Robot.switchToCamera(0);
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		Robot.switchToCamera(0);
		climber.kill();
		throw new Error("CLIMB COMMAND INTERRUPTED. THIS IS VERY DANGEROUS.");
	}
}
